language: node_js
node_js:
  - "5"
env:
  - NODE_ENV=ci
before_script:
  - npm run setup
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm test
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
